services:
  - docker

# The following code should reflect the one from luaunit.ps1
before_install:
  - docker build --tag=luaunit:5.1 tests

script: docker run --rm --user $UID:$UID --volume $(pwd):/app --workdir /app luaunit:5.1 lua tests/TestSuite.lua
