services:
  - docker

before_install:
  - docker-compose build lua
  - docker-compose build luarocks
  - docker-compose build busted

script:
  - sudo chmod +x docker/busted/entry-point.sh
  - docker-compose run --rm busted -v
