services:
  - docker

before_install:
  - docker-compose build

script:
  - sudo chmod +x docker/entry-point.sh
  - docker-compose run luaunit tests/UnitTestSuite.lua -v
  - docker-compose run luaunit tests/AcceptanceTestSuite.lua -v
