version: '3'

services:

  lua:
    build:
      context: ./docker/lua
    image: lua:5.1

  luarocks:
    build:
      context: ./docker/luarocks
    image: luarocks:5.1
    working_dir: /luarocks
    volumes:
      - ./docker/luarocks:/luarocks/modules
      - ./docker:/luarocks/docker
    depends_on:
      - lua

  busted:
    build:
      context: ./docker/busted
    image: busted:5.1
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - luarocks
