version: '3'
services:
  luaunit:
    user: root
    build:
      context: ./docker
    image: eso-lua:5.1
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_ENV=${APP_ENV}
