--describe("Start pomodoro", function()
--    -- See https://github.com/rdok/eso-pomodoro/issues/3
--
--    setup(function()
--        require 'TestCase'
--    end)
--
--    it("a player may start a pomodoro", function()
--        -- Given I am acting as a player
--        -- When I start a new pomodoro
--        StartCommand.new()
--        -- Then i should see 'Pomodoro started' message
--    end)
--
--    it("a user may start a pomodoro", function()
--    end)
--
--    it("should have access to help command when using 'help' as second command", function()
--        spy.on(HelpCommand, "new")
--        Command.call('help')
--        assert.spy(HelpCommand.new).was_called()
--    end)
--
--end)
